name: Run Github API Tests with Robot Framework

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
    inputs:
      run_notes:
        description: 'Notes'
        required: false
        default: ''
        type: string

run-name: Robot Framework API Tests | ${{inputs.run_notes}}

permissions:
  contents: read
  pages: write
  id-token: write


concurrency:
  group: "pages"
  cancel-in-progress: false


jobs:
    run_tests:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.x'

        - name: Install dependencies
          run: |
            python -m venv venv
            source venv/bin/activate
            pip install -r robot_framework/requirements.txt

        - name: Run Robot Framework tests
          env:
            GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
          run: |
            source venv/bin/activate
            mkdir -p robot_framework/report
            pabot --testlevelsplit --processes 5 --listener RetryFailed:1 --loglevel WARN --removekeywords NAME:base_keywords.Set_Github_Header --output robot_framework/report/output.xml --log robot_framework/report/log.html --report robot_framework/report/report.html robot_framework/tests | tee robot_framework/report/pabot_output.txt
            mv robot_framework/report/report.html robot_framework/report/index.html

        
        - name: Upload Robot Framework test results
          if: always()
          id: upload-artifact
          uses: actions/upload-artifact@v4.6.2
          with:
            name: robot-framework-results
            path: robot_framework/report/


        - name: Display Results
          if: ${{ steps.upload-artifact.outcome == 'success' }}
          run: |
            echo "Robot Framework test results have been uploaded as an artifact."
            ls -la robot_framework/report/
            SUMMARY_LINE=$(grep -E '^[0-9]+ tests, [0-9]+ passed, [0-9]+ failed, [0-9]+ skipped' robot_framework/report/pabot_output.txt)
            echo "## Test Summary" >> $GITHUB_STEP_SUMMARY
            echo "$SUMMARY_LINE" >> $GITHUB_STEP_SUMMARY


    deploy_results_page:
      needs: run_tests
      if: ${{ github.ref == 'refs/heads/main' }}

      environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}

      runs-on: ubuntu-latest

      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Setup Pages
          uses: actions/configure-pages@v5

        - name: Download artifact
          uses: actions/download-artifact@v5
          with:
            name: robot-framework-results
            path: robot_framework/robot-framework-results

        - name: List files and folders
          run: |
            ls 
            ls robot_framework/
            ls -la robot_framework/robot-framework-results

        - name: Upload artifact
          uses: actions/upload-pages-artifact@v3
          env:
            GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
          with:
            path: 'robot_framework/robot-framework-results'

        - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v4
